### ISSUE TITLE
Support for Paperclip attachments

### ISSUE THREAD

**Issue by avishai** [neerajsingh0101/admin_data#6]
It would be great to include support for displaying Paperclip attachments within the interface. Some sort of funcitonality to include the thumbnail, which you can specify in the configuration.

Great plugin!

**Comment by neerajsingh0101** [comment]
There are many different plugins to handle attachments and there are way too many different ways attachments can be handled. I think ,at this point of time, I would concentrate more of enriching the functionality around other areas of admin_data than trying to solve the attachment issue.

Having said that if you send me a patch then I will surely look at it.

Some people contacted me to have similar functionality but they were using attachment_fu. May be I should think about exposing some kind of hook so that other plugins can rely on this plugin to get their attachment working as they want.

**Comment by neerajsingh0101** [comment]
Providing support for attached items is tricky and hence will not be taken up.

Closing this issue.
