### ISSUE TITLE
field is exactly "" returns all fields

### ISSUE THREAD

**Issue by rdp** [neerajsingh0101/admin_data#77]
Hello.
When I use admin_data (rails2 here), and I choose "advance search" and say "original_url" "is exactly" and leave the third field blank, I'd expect to find all product's with a blank description.
Instead, it seems to show _all_ products, as if it were ignoring the query.
(As a side note, having the query params as GET params might be nicer for bookmarkable queries).
Cheers!
-roger-

**Comment by neerajsingh0101** [comment]
Hi rdp,

You are right. It does not work very well with blank entries. 

Since you are working on rails 2 branch, I can't really do much since I do not have time to support Rails 2 branch.

When you upgrade your app to Rails3 then try out the newest gem and hopefully that will fix your problem.

Thanks
